### ISSUE TITLE
/src/components/RecipeCards/recipecards.js

### ISSUE THREAD

**Issue by kathyboilek** [kathyboilek/Classic-Pairings#12]
webpackHotDevClient.js:120 ./src/components/RecipeCards/recipecards.js
  Line 3:   'CardText' is defined but never used                                                                                          no-unused-vars
  Line 4:   'CardSubtitle' is defined but never used                                                                                      no-unused-vars
  Line 4:   'Button' is defined but never used                                                                                            no-unused-vars
  Line 15:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
printWarnings @ webpackHotDevClient.js:120

**Comment by deboragaleli** [comment]
I already deleted undefined components and fixed the rel="noopener noreferrer". Thank you.
