### ISSUE TITLE
 ./src/components/NavBar/navbar.js

### ISSUE THREAD

**Issue by kathyboilek** [kathyboilek/Classic-Pairings#14]
webpackHotDevClient.js:120 ./src/components/NavBar/navbar.js
  Line 50:  The href attribute requires a valid address. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
  Line 56:  The href attribute requires a valid address. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
printWarnings @ webpackHotDevClient.js:120

**Comment by deboragaleli** [comment]
This issue can be solved as soon as we get the authentication to work. Thank you.
