### ISSUE TITLE
 ./src/components/HomeCarousel/homecarousel.js

### ISSUE THREAD

**Issue by kathyboilek** [kathyboilek/Classic-Pairings#16]
webpackHotDevClient.js:120 ./src/components/HomeCarousel/homecarousel.js
  Line 9:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 10:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 11:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 12:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 13:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 14:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
printWarnings @ webpackHotDevClient.js:120

**Comment by deboragaleli** [comment]
Issued solved when I added images to the carousel. Thank you!
